<ul>
<li><strong>Version 3.2</strong> - 9 Oktober 2017
	<ul>
	<li>Export/import settings via XML file (FR #8341) Sponsored by Visionpark</li>
	<li>Fixed: Show tabcontent of Tabs when there are no field definitions</li>
	<li>Fixed: Delete tabfield reference after a field definition has been deleted</li>
	<li>Fixed: Drop tab related tables from the database with uninstall action</li>
	</ul>
</li>
<li><strong>Version 3.1</strong> - 21 July 2017
	<ul>
	<li>Added fieldtype 'FilePicker'</li>
	</ul>
</li>
<li><strong>Version 3.0</strong> - 15 October 2016
	<ul>
	<li>Added fieldtype 'Page selector' (FR #10077)</li>
	<li>Grouping of settings by custom tabs (FR #10176)</li>
	<li>Clicking on fieldtype button fires event 'OnSettingChange'</li>
	</ul>
</li>
<li><strong>Version 2.2</strong> - 13 March 2016
	<ul>
	<li>Tag {CustomGS} no longer needed, module gets automatically initialized</li>
	<li>Added fieldtype 'JMFilePicker'</li>
	<li>New icon</li>
	<li>Use core cms_mailer method</li>
	<li>Minimum required CMSms version set to 1.12</li>
	<li>Bug #10838: fixed - Doesn't output anything in 2.1.1</li>
	<li>Bug #10932: fixed - Permissions not checked properly</li>
	</ul>
</li>
<li><strong>Version 2.1</strong> - 10 July 2014
	<ul>
	<li>Bug #9989: fixed - Hidden field values are reset to "0"</li>
	</ul>
</li>
<li><strong>Version 2.0</strong> - 21 May 2014
	<ul>
	<li>Fixes for Core 2.0</li>
	<li>Minimum required CMSms version set to 1.11</li>
	</ul>
</li>
<li><strong>Version 1.6</strong> - 19 May 2014
	<ul>
	<li>Minor style update for collapsible fieldset (FR #9939)</li>
	<li>Bug #9989: fixed - Hidden field values are reset to "0"</li>
	</ul>
</li>
<li><strong>Version 1.5</strong> - 5 December 2013
	<ul>
	<li>Possibility to add admin page under Site Admin section. Editors don't have access!</li>
	<li>Added fieldtype 'ColorPicker' (thanks to Jissey)</li>
	<li>Added French translation (thanks to Jissey)</li>
	<li>Added collapsible fieldgroups (FR #8166, #8517 and #9465)</li>
	<li>Added the ability to assign each field to 'admin' or 'editor' (FR #8515)</li>
	</ul>
</li>
<li><strong>Version 1.4</strong> - 9 May 2013
	<ul>
	<li>Drag and drop field ordering (FR #8516)</li>
	<li>Added fieldtype 'GBFilePicker' (FR #8286 and #8634)</li>
	<li>Included Wiki helptext and examples in the module helptext</li>
	<li>Bug #8633: fixed - Does not escape help text</li>
	<li>Bug #9019: fixed - Submit not working for those without 'Manage' permissions</li>
	</ul>
</li>
<li><strong>Version 1.3</strong> - 14 August 2012
	<ul>
	<li>Removed Clear Cache due to Forge regulations</li>
	<li>Bug #8009: fixed - Issue with text areas with smarty parsing on</li>
	</ul>
</li>
<li><strong>Version 1.2</strong> - 20 March 2012
	<ul>
	<li>Minimum required CMSms version set to 1.10</li>
	<li>Add GetAdminSection setting (FR #7618)</li>
	<li>Added option to automatically clear cache after changing a setting</li>
	<li>Added fieldtype 'Button'</li>
	<li>Support Value|OptionName pairs and Smarty tags for pulldown fields and radiobuttons</li>
	<li>Bug fixed: Editing a field changes the fieldname</li>
	<li>Bug fixed: SendEvent on changing a checkbox setting</li>
	</ul>
</li>
<li><strong>Version 1.1</strong> - 19 February 2012
	<ul>
	<li>Define unlimited number of fields</li>
	<li>Added fieldtypes textarea, wysiwyg, datetimepicker, pulldown select, radiobuttons</li>
	<li>Added event OnSettingChange</li>
	</ul>
</li>
<li><strong>Version 1.0</strong> - 21 January 2012
	<ul>
	<li>Initial module release</li>
	</ul>
</li>
</ul>