<ul>
<li>2.2.1 - December, 2018
   <ul>
   <li>Minor improvement (v2.3 compatibility) for module_action_link.</li>
   </ul>
<li>
<li>2.2 - December 2018
	<ul>
	<li>Minor fixes.</li>
	<ul>
</li>
<li>2.1 - April 2016
	<ul>
	<li>Added the {setvar},{unsetvar}, and  {getvar} plugins.</li>
	</ul>
	</lI>

<li>2.0 - June 2015 (start of branch for 2.0)<br/>
  <p class="warning"><strong>Warning:</strong> This module is not 100% compatible with the versions released for CMSMS 1.x</p>
  <ul>
  <li>Removed the cgsi_array_set and cgsi_array_unset plugins.</li>
  <li>Removed assign argument from cgsimple methods.</li>
  <li>Added cgsimple::get_parallel_content() and cgsimple::get_parallel_url()</li>
  </ul>
  </li>

<li>1.9.1 - May 2015
  <ul>
	<li>Now gets rid of the {$cgsimple} smarty variable. now use {cgsimple::method} instead (for cmsms 2.0 and non-permissive smarty)</li>
  </ul>
  </li>

<li>1.9 - May 2015
  <ul>
	<li>Adds the {anchor_link} plugin.</li>
	<li>Adds cgsimple::anchor_url() method.</li>
  </ul>
</li>
<li>1.8 - April 2015
  <ul>
   <li>Adds the {module_action_url} plugin.</li>
  </ul>
</li>
<li>1.7.4 - July 2014
  <ul>
    <li>Adds more parameters to {module_action_link}</li>
  </ul>
</li>

<li>1.7.3 - June 2014
  <ul>
    <li>Fixes for CMSMS 2.0</li>
    <li>Minor enhancement to module_action_link</li>
  </ul>
</li>

<li>1.7.x - July 2013
  <ul>
    <li>Adds automatic detection of module parameter for {module_action_link} <em>(1.7.1)</em></li>
    <li>Adds the cgsimple::get_parallel_page function.</li>
  </ul>
</li>
<li>1.6.1 - April 2013
  <ul>
    <li>Minor bug fix.</li>
  </ul>
</li>
<li>1.6 - March 2013
  <ul>
    <li>Fixes bugs.  Moves most methods static.</li>
    <li>Requires PHP 5.3.</li>
    <li>Bug fixes.</li>
  </ul>
</li>
<li>1.5.1 - July 2012
 <ul>
   <li>Move help external.</li>
   <li>Fix to hasChildren method.</li>
   <li>Minor code cleanup.</li>
 </ul>
</li>
<li>1.5 - October 2011
<p>A couple more useful smarty plugins.</p>
</li>
<li>1.4.10 - October 2011
<p>More Fixes for CMSMS 1.10</p>
</li>
<p>Fixes for CMSMS 1.10</p>
</li>
<li>1.4.6 - December 2010
<p>Fixed the help for the get_page_type method.</p>
</li>
<li>1.4.5 - June. 2010
<p>Adds the $cgsimple->get_page_type() method.</p>
</li>
<li>1.4.4 - Feb. 2010
   <p>Minor help fixes.</p>
   <p>Minor bug fixes.</p>
</li>
<li>1.4.3 - July, 2009
   <p>Fixes for 1.6 compatibility.</p>
</li>
<li>1.4.2 - Apr, 2009
   <p>Add the jsfriendly param to module_action_link</p>
</li>
<li>1.4.1 - Feb, 2009
   <p>Fixes to module_action_link</p>
</li>
<li>1.4 - Jan, 2009
   <p>Add the session_erase, session_put, and self_url plugins.</p>
</li>
<li>1.3.3 - Dec, 2008
    <p>No longer handle events.</li>
</li>
<li>1.3.2 - Dec, 2008
    <p>Bug Fixes.</p>
    <p>Move changelog to seperate file.</p>
    <p>Add get_sibling() smarty method.</p>
</li>
<li>1.3.1 - May, 2008
    <p>Minor fix to the module_action plugin</p>
</li>
<li>1.3 - March, 2008
  <p>Add the get_children method</p>
</li>
<li>1.2.1 - March, 2008
  <p>Minor fix for module_action_link</p>
</li>
<li>1.2 - March, 2008
  <p>Add the cgrepeat smarty plugin</p>
  <p>Add image support to the module_action_link smarty plugin</p>
  <p>Update copyright and license</p>
</li>
<li>1.1.1 - February, 2008
  <p>Fix minor problem with the module_exists method</p>
</li>
<li>1.1 - February, 2008
  <p>Added get_page_menutext() method</p>
  <p>Added module_action_link</p>
</li>
<li>1.0 - December, 2007
  <p>Initial release</p>
</li>
</ul>
