<h3>Version 1.3.1 - 12Jul17</h3>
<ul>
   <li>minor bug fix</li>
</ul>
<br>

<h3>Version 1.3 - 11Jul17</h3>
<ul>
   <li>sortablelist - added max_number and required_number options</li>
   <li>Added 'fieldset_start' and 'fieldset_end' fields</li>
</ul>
<br>

<h3>Version 1.2.2 - 05Jul17</h3>
<ul>
   <li>test for and display warning in admin if UDT does not exist</li>
</ul>
<br>

<h3>Version 1.2.1 - 19Apr17</h3>
<ul>
   <li>bug fix for color_picker, default_value - BR#11354 - thanks Stuart</li>
   <li>color_picker - tweaked layout</li>
   <li>sortablelist - now use jquery sortable instead of CGExtensions. Parameters removed: 'template'. Parameters not operational: 'max_selected', 'allowduplicates' (please advise if you require these). Plus some bug fixes.</li>
</ul>
<br>

<h3>Version 1.2 - 07Nov16</h3>
<ul>
   <li>Added 'description' parameter for all fields (optional) - adds additional text explanation for editor</li>
   <li>Added 'hidden' field - Can be used to set a page attribute that can then be accessed (e.g. from a Navigator-Template), using {page_attr page=$node->alias key='testhidden'}</li>
   <li>Bug fix - for php notice</li>
</ul>
<br>

<h3>Version 1.1 - 15Apr16</h3>
<ul>
    <li>Bug fix</li>
</ul>
<br>

<h3>Version 1.0 - 15Apr16</h3>
<ul>
    <li>Initial release. A fork of ECB module v1.6, that is compatible with CMSMS v2+</li>
    <li>Added radio field - to provide radio buttons on an admin page</li>
</ul>
<br>
